USE auth;

ALTER TABLE users
    ADD COLUMN first_name VARCHAR(100) DEFAULT NULL AFTER email_verified,
    ADD COLUMN last_name VARCHAR(100) DEFAULT NULL AFTER first_name,
    ADD COLUMN date_of_birth DATE DEFAULT NULL AFTER last_name,
    ADD COLUMN phone VARCHAR(20) DEFAULT NULL AFTER date_of_birth,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
